"use client";

import { ALBUM_TEMPLATES, LAYOUT_LIBRARY } from "@wedding/config";
import { LayoutPreview } from "@/components/layout-preview";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

/** The 12 Photoshop album page templates with live layout previews. */
export default function TemplatesPage() {
  return (
    <div className="space-y-6">
      <header>
        <h1 className="font-display text-3xl tracking-wide">Album Templates</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Twelve PSD page designs generated by the Photoshop agent: DESIGN, PHOTOS (Smart Objects)
          and TEXT groups. Designs are rebuilt on the agent on first run.
        </p>
      </header>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        {ALBUM_TEMPLATES.map((t) => {
          const layout = LAYOUT_LIBRARY[t.defaultLayout];
          return (
            <Card key={t.key}>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">
                  {t.key} — {t.title}
                </CardTitle>
                <CardDescription>{t.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <LayoutPreview slots={layout?.slots ?? []} label={layout?.name} />
                <div className="mt-2 flex gap-1">
                  <Badge variant="neutral">{layout?.slots.length ?? 0} photos</Badge>
                  <Badge variant="neutral">Smart Objects</Badge>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
